import { Button, Container } from "@chakra-ui/react";
import Head from "next/head";

export default function Kitchen() {
    return (
        <>
        <Head>
            <title> Buttons tryouts </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Container>
            <Button></Button>
        </Container>
        </>
    );
}